// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TimeSheet.Data.Data;

#nullable disable

namespace TimeSheet.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250523063951_RenameTypo")]
    partial class RenameTypo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TimeSheet.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Business Development"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Operations"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Finance & Payroll"
                        },
                        new
                        {
                            Id = 4,
                            Name = "HR"
                        },
                        new
                        {
                            Id = 5,
                            Name = "IT"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Marketing"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Legal"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Admin/Facilities"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Company Secretary"
                        },
                        new
                        {
                            Id = 10,
                            Name = "ED"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Business Vertical Head"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Project Managers"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Bid Managers"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Project Coordinators"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Project Team Members"
                        });
                });

            modelBuilder.Entity("TimeSheet.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ApproverId")
                        .HasColumnType("int");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ApproverId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("TimeSheet.Models.Milestone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Milestones");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartmentId = 1,
                            Description = "CV search, CV preparation, formatting, fee sheet, A & M, EMD Preparation, Proposal compilation",
                            Name = "Bid Preparation"
                        },
                        new
                        {
                            Id = 2,
                            DepartmentId = 1,
                            Description = "Tender scanning, meeting prospective clients, Networking with tenderers",
                            Name = "Pipeline creation"
                        },
                        new
                        {
                            Id = 3,
                            DepartmentId = 1,
                            Description = "capdoc, brochure preparation, project Information sheet",
                            Name = "BD support work"
                        },
                        new
                        {
                            Id = 4,
                            DepartmentId = 1,
                            Description = "",
                            Name = "Bid analysis / reporting"
                        },
                        new
                        {
                            Id = 5,
                            DepartmentId = 1,
                            Description = "",
                            Name = "Learning and development"
                        },
                        new
                        {
                            Id = 6,
                            DepartmentId = 1,
                            Description = "",
                            Name = "Audit & Compliances"
                        },
                        new
                        {
                            Id = 7,
                            DepartmentId = 1,
                            Description = "",
                            Name = "Additional"
                        },
                        new
                        {
                            Id = 8,
                            DepartmentId = 2,
                            Description = "",
                            Name = "Invoicing"
                        },
                        new
                        {
                            Id = 9,
                            DepartmentId = 2,
                            Description = "",
                            Name = "Procurement"
                        },
                        new
                        {
                            Id = 10,
                            DepartmentId = 2,
                            Description = "",
                            Name = "ERP"
                        },
                        new
                        {
                            Id = 11,
                            DepartmentId = 2,
                            Description = "",
                            Name = "Contract Management"
                        },
                        new
                        {
                            Id = 12,
                            DepartmentId = 2,
                            Description = "",
                            Name = "Project/ Business Performance Analysis and Reporting"
                        },
                        new
                        {
                            Id = 13,
                            DepartmentId = 2,
                            Description = "",
                            Name = "ERP Customization"
                        },
                        new
                        {
                            Id = 14,
                            DepartmentId = 2,
                            Description = "",
                            Name = "Additional"
                        },
                        new
                        {
                            Id = 15,
                            DepartmentId = 3,
                            Description = "",
                            Name = "Financial Statements preparation and analysis"
                        },
                        new
                        {
                            Id = 16,
                            DepartmentId = 3,
                            Description = "",
                            Name = "Payments"
                        },
                        new
                        {
                            Id = 17,
                            DepartmentId = 3,
                            Description = "",
                            Name = "Taxation"
                        },
                        new
                        {
                            Id = 18,
                            DepartmentId = 3,
                            Description = "",
                            Name = "Banking"
                        },
                        new
                        {
                            Id = 19,
                            DepartmentId = 3,
                            Description = "",
                            Name = "Learning and Development"
                        },
                        new
                        {
                            Id = 20,
                            DepartmentId = 3,
                            Description = "",
                            Name = "Audit & Compliances"
                        },
                        new
                        {
                            Id = 21,
                            DepartmentId = 3,
                            Description = "",
                            Name = "Additional"
                        },
                        new
                        {
                            Id = 22,
                            DepartmentId = 4,
                            Description = "",
                            Name = "Talent acquisition"
                        },
                        new
                        {
                            Id = 23,
                            DepartmentId = 4,
                            Description = "",
                            Name = "HR Administration"
                        },
                        new
                        {
                            Id = 24,
                            DepartmentId = 4,
                            Description = "",
                            Name = "Performance Management, R&R"
                        },
                        new
                        {
                            Id = 25,
                            DepartmentId = 4,
                            Description = "",
                            Name = "Succession Planning/Leadership Development"
                        },
                        new
                        {
                            Id = 26,
                            DepartmentId = 4,
                            Description = "",
                            Name = "Training & Development"
                        },
                        new
                        {
                            Id = 27,
                            DepartmentId = 4,
                            Description = "",
                            Name = "Audit & Compliances"
                        },
                        new
                        {
                            Id = 28,
                            DepartmentId = 4,
                            Description = "",
                            Name = "Additional"
                        },
                        new
                        {
                            Id = 29,
                            DepartmentId = 5,
                            Description = "",
                            Name = "Hardware/Software procurement"
                        },
                        new
                        {
                            Id = 30,
                            DepartmentId = 5,
                            Description = "",
                            Name = "IT Support/troubleshooting"
                        },
                        new
                        {
                            Id = 31,
                            DepartmentId = 5,
                            Description = "",
                            Name = "Network/Server maintenance"
                        },
                        new
                        {
                            Id = 32,
                            DepartmentId = 5,
                            Description = "",
                            Name = "Digital innovation support"
                        },
                        new
                        {
                            Id = 33,
                            DepartmentId = 5,
                            Description = "",
                            Name = "Learning and Development"
                        },
                        new
                        {
                            Id = 34,
                            DepartmentId = 5,
                            Description = "",
                            Name = "SLA/Policy Compliance"
                        },
                        new
                        {
                            Id = 35,
                            DepartmentId = 5,
                            Description = "",
                            Name = "Additional"
                        },
                        new
                        {
                            Id = 36,
                            DepartmentId = 6,
                            Description = "",
                            Name = "Brand/Corporate Communication"
                        },
                        new
                        {
                            Id = 37,
                            DepartmentId = 6,
                            Description = "",
                            Name = "Marketing Material development"
                        },
                        new
                        {
                            Id = 38,
                            DepartmentId = 6,
                            Description = "",
                            Name = "Digital Marketing"
                        },
                        new
                        {
                            Id = 39,
                            DepartmentId = 6,
                            Description = "",
                            Name = "Association Membership and networking"
                        },
                        new
                        {
                            Id = 40,
                            DepartmentId = 6,
                            Description = "",
                            Name = "Learning & Development"
                        },
                        new
                        {
                            Id = 41,
                            DepartmentId = 6,
                            Description = "",
                            Name = "Audit/ Compliances"
                        },
                        new
                        {
                            Id = 42,
                            DepartmentId = 6,
                            Description = "",
                            Name = "Additional"
                        },
                        new
                        {
                            Id = 43,
                            DepartmentId = 7,
                            Description = "",
                            Name = "Contract drafting & Review"
                        },
                        new
                        {
                            Id = 44,
                            DepartmentId = 7,
                            Description = "",
                            Name = "Handling legal issues and cases"
                        },
                        new
                        {
                            Id = 45,
                            DepartmentId = 7,
                            Description = "",
                            Name = "REIT"
                        },
                        new
                        {
                            Id = 46,
                            DepartmentId = 7,
                            Description = "",
                            Name = "Learning & Development"
                        },
                        new
                        {
                            Id = 47,
                            DepartmentId = 7,
                            Description = "",
                            Name = "Audit/ Compliances"
                        },
                        new
                        {
                            Id = 48,
                            DepartmentId = 7,
                            Description = "",
                            Name = "Additional"
                        },
                        new
                        {
                            Id = 49,
                            DepartmentId = 8,
                            Description = "",
                            Name = "Hiring/ de-hiring of premises/ Guest Houses"
                        },
                        new
                        {
                            Id = 50,
                            DepartmentId = 8,
                            Description = "Maintaining Asset Register and tracking asset utilisation",
                            Name = "Procurement/Disposal of furniture, fixtures, monthly consumables"
                        },
                        new
                        {
                            Id = 51,
                            DepartmentId = 8,
                            Description = "Air/rail/Cab booking",
                            Name = "Travel Booking"
                        },
                        new
                        {
                            Id = 52,
                            DepartmentId = 8,
                            Description = "",
                            Name = "Handling office boys, security"
                        },
                        new
                        {
                            Id = 53,
                            DepartmentId = 8,
                            Description = "",
                            Name = "Learning & Development"
                        },
                        new
                        {
                            Id = 54,
                            DepartmentId = 8,
                            Description = "",
                            Name = "Audit/ Compliances"
                        },
                        new
                        {
                            Id = 55,
                            DepartmentId = 8,
                            Description = "",
                            Name = "Additional"
                        },
                        new
                        {
                            Id = 56,
                            DepartmentId = 9,
                            Description = "",
                            Name = "Secretarial"
                        },
                        new
                        {
                            Id = 57,
                            DepartmentId = 9,
                            Description = "",
                            Name = "Fund Raising"
                        },
                        new
                        {
                            Id = 58,
                            DepartmentId = 9,
                            Description = "",
                            Name = "Acquisition"
                        },
                        new
                        {
                            Id = 59,
                            DepartmentId = 9,
                            Description = "",
                            Name = "REIT"
                        },
                        new
                        {
                            Id = 60,
                            DepartmentId = 9,
                            Description = "",
                            Name = "Learning & Development"
                        },
                        new
                        {
                            Id = 61,
                            DepartmentId = 9,
                            Description = "",
                            Name = "Audit & Compliances"
                        },
                        new
                        {
                            Id = 62,
                            DepartmentId = 9,
                            Description = "",
                            Name = "Additional"
                        },
                        new
                        {
                            Id = 63,
                            DepartmentId = 10,
                            Description = "",
                            Name = "Business Development - Pipeline creation"
                        },
                        new
                        {
                            Id = 64,
                            DepartmentId = 10,
                            Description = "",
                            Name = "Business Development - Bidding"
                        },
                        new
                        {
                            Id = 65,
                            DepartmentId = 10,
                            Description = "",
                            Name = "New Product/service development"
                        },
                        new
                        {
                            Id = 66,
                            DepartmentId = 10,
                            Description = "",
                            Name = "Business Performance support and Analysis"
                        },
                        new
                        {
                            Id = 67,
                            DepartmentId = 10,
                            Description = "",
                            Name = "Learning & Development"
                        },
                        new
                        {
                            Id = 68,
                            DepartmentId = 10,
                            Description = "",
                            Name = "Audit & Compliances"
                        },
                        new
                        {
                            Id = 69,
                            DepartmentId = 10,
                            Description = "",
                            Name = "Additional"
                        },
                        new
                        {
                            Id = 70,
                            DepartmentId = 11,
                            Description = "",
                            Name = "Business Development - Pipeline creation"
                        },
                        new
                        {
                            Id = 71,
                            DepartmentId = 11,
                            Description = "",
                            Name = "Business Development - Bidding"
                        },
                        new
                        {
                            Id = 72,
                            DepartmentId = 11,
                            Description = "",
                            Name = "Project Quality Delivery"
                        },
                        new
                        {
                            Id = 73,
                            DepartmentId = 11,
                            Description = "",
                            Name = "Project and Business Administration"
                        },
                        new
                        {
                            Id = 74,
                            DepartmentId = 11,
                            Description = "",
                            Name = "Learning & Development"
                        },
                        new
                        {
                            Id = 75,
                            DepartmentId = 11,
                            Description = "",
                            Name = "Audit & Compliances"
                        },
                        new
                        {
                            Id = 76,
                            DepartmentId = 11,
                            Description = "",
                            Name = "Additional"
                        },
                        new
                        {
                            Id = 77,
                            DepartmentId = 12,
                            Description = "",
                            Name = "Business Development - Pipeline creation"
                        },
                        new
                        {
                            Id = 78,
                            DepartmentId = 12,
                            Description = "",
                            Name = "Business Development - Bidding"
                        },
                        new
                        {
                            Id = 79,
                            DepartmentId = 12,
                            Description = "",
                            Name = "Project Quality Delivery"
                        },
                        new
                        {
                            Id = 80,
                            DepartmentId = 12,
                            Description = "",
                            Name = "Project Commercial success"
                        },
                        new
                        {
                            Id = 81,
                            DepartmentId = 12,
                            Description = "",
                            Name = "Learning & Development"
                        },
                        new
                        {
                            Id = 82,
                            DepartmentId = 12,
                            Description = "",
                            Name = "Audit & Compliances"
                        },
                        new
                        {
                            Id = 83,
                            DepartmentId = 12,
                            Description = "",
                            Name = "Additional"
                        },
                        new
                        {
                            Id = 84,
                            DepartmentId = 13,
                            Description = "",
                            Name = "Business Development - Pipeline creation"
                        },
                        new
                        {
                            Id = 85,
                            DepartmentId = 13,
                            Description = "",
                            Name = "Business Development - Bidding"
                        },
                        new
                        {
                            Id = 86,
                            DepartmentId = 13,
                            Description = "",
                            Name = "Bid Quality Delivery"
                        },
                        new
                        {
                            Id = 87,
                            DepartmentId = 13,
                            Description = "",
                            Name = "Bid Commercial success"
                        },
                        new
                        {
                            Id = 88,
                            DepartmentId = 13,
                            Description = "",
                            Name = "Learning & Development"
                        },
                        new
                        {
                            Id = 89,
                            DepartmentId = 13,
                            Description = "",
                            Name = "Audit & Compliances"
                        },
                        new
                        {
                            Id = 90,
                            DepartmentId = 13,
                            Description = "",
                            Name = "Additional"
                        },
                        new
                        {
                            Id = 91,
                            DepartmentId = 14,
                            Description = "",
                            Name = "Business Development - Pipeline creation"
                        },
                        new
                        {
                            Id = 92,
                            DepartmentId = 14,
                            Description = "",
                            Name = "Business Development - Bidding"
                        },
                        new
                        {
                            Id = 93,
                            DepartmentId = 14,
                            Description = "",
                            Name = "Project Quality Delivery"
                        },
                        new
                        {
                            Id = 94,
                            DepartmentId = 14,
                            Description = "",
                            Name = "Project Commercial success"
                        },
                        new
                        {
                            Id = 95,
                            DepartmentId = 14,
                            Description = "",
                            Name = "Learning & Development"
                        },
                        new
                        {
                            Id = 96,
                            DepartmentId = 14,
                            Description = "",
                            Name = "Audit & Compliances"
                        },
                        new
                        {
                            Id = 97,
                            DepartmentId = 14,
                            Description = "",
                            Name = "Additional"
                        },
                        new
                        {
                            Id = 98,
                            DepartmentId = 15,
                            Description = "",
                            Name = "Learning & Development"
                        },
                        new
                        {
                            Id = 99,
                            DepartmentId = 15,
                            Description = "",
                            Name = "Audit & Compliances"
                        },
                        new
                        {
                            Id = 100,
                            DepartmentId = 15,
                            Description = "",
                            Name = "Additional"
                        });
                });

            modelBuilder.Entity("TimeSheet.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("ProjectCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("TimeSheet.Models.ProjectMilestone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<long>("AssignedHours")
                        .HasColumnType("bigint");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("MilestoneCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MilestoneDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("PendingWorkingHours")
                        .HasColumnType("bigint");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("RejectionRemarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaskCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaskDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TimeSheetLineNumber")
                        .HasColumnType("int");

                    b.Property<string>("TimeSheetNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("TotalWorkingHours")
                        .HasColumnType("bigint");

                    b.Property<string>("WbsId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectMilestones");
                });

            modelBuilder.Entity("TimeSheet.Models.Timesheet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<long>("Hours")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsBillable")
                        .HasColumnType("bit");

                    b.Property<int?>("MilestoneId")
                        .HasColumnType("int");

                    b.Property<int?>("ProjectMilestoneId")
                        .HasColumnType("int");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("MilestoneId");

                    b.HasIndex("ProjectMilestoneId");

                    b.ToTable("Timesheets");
                });

            modelBuilder.Entity("TimeSheet.Models.WorkingHours", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("Hours")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("WorkingHours");
                });

            modelBuilder.Entity("TimeSheet.Models.Employee", b =>
                {
                    b.HasOne("TimeSheet.Models.Employee", "Approver")
                        .WithMany()
                        .HasForeignKey("ApproverId");

                    b.HasOne("TimeSheet.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Approver");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("TimeSheet.Models.Milestone", b =>
                {
                    b.HasOne("TimeSheet.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("TimeSheet.Models.Project", b =>
                {
                    b.HasOne("TimeSheet.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("TimeSheet.Models.ProjectMilestone", b =>
                {
                    b.HasOne("TimeSheet.Models.Project", "Project")
                        .WithMany("ProjectMilestones")
                        .HasForeignKey("ProjectId");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("TimeSheet.Models.Timesheet", b =>
                {
                    b.HasOne("TimeSheet.Models.Employee", "Employee")
                        .WithMany("Timesheets")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TimeSheet.Models.Milestone", "Milestone")
                        .WithMany()
                        .HasForeignKey("MilestoneId");

                    b.HasOne("TimeSheet.Models.ProjectMilestone", "ProjectMilestone")
                        .WithMany("Timesheets")
                        .HasForeignKey("ProjectMilestoneId");

                    b.Navigation("Employee");

                    b.Navigation("Milestone");

                    b.Navigation("ProjectMilestone");
                });

            modelBuilder.Entity("TimeSheet.Models.WorkingHours", b =>
                {
                    b.HasOne("TimeSheet.Models.Employee", "Employee")
                        .WithMany("WorkingHours")
                        .HasForeignKey("EmployeeId");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("TimeSheet.Models.Employee", b =>
                {
                    b.Navigation("Timesheets");

                    b.Navigation("WorkingHours");
                });

            modelBuilder.Entity("TimeSheet.Models.Project", b =>
                {
                    b.Navigation("ProjectMilestones");
                });

            modelBuilder.Entity("TimeSheet.Models.ProjectMilestone", b =>
                {
                    b.Navigation("Timesheets");
                });
#pragma warning restore 612, 618
        }
    }
}
