// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TimeSheet.Data.Data;

#nullable disable

namespace TimeSheet.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250530080407_AddApproverIdinSubmissionLog")]
    partial class AddApproverIdinSubmissionLog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TimeSheet.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Business Development"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Operations"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Finance & Payroll"
                        },
                        new
                        {
                            Id = 4,
                            Name = "HR"
                        },
                        new
                        {
                            Id = 5,
                            Name = "IT"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Marketing"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Legal"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Admin/Facilities"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Company Secretary"
                        },
                        new
                        {
                            Id = 10,
                            Name = "ED"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Business Vertical Head"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Project Managers"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Bid Managers"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Project Coordinators"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Project Team Members"
                        });
                });

            modelBuilder.Entity("TimeSheet.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ApproverId")
                        .HasColumnType("int");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ApproverId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("TimeSheet.Models.Milestone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Milestones");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartmentId = 1,
                            Name = "Bid Preparation",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 2,
                            DepartmentId = 1,
                            Name = "Pipeline creation",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 3,
                            DepartmentId = 1,
                            Name = "BD support work",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 4,
                            DepartmentId = 1,
                            Name = "Bid analysis / reporting",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 5,
                            DepartmentId = 1,
                            Name = "Learning and development",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 6,
                            DepartmentId = 1,
                            Name = "Audit & Compliances",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 7,
                            DepartmentId = 1,
                            Name = "Additional",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 8,
                            DepartmentId = 2,
                            Name = "Invoicing",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 9,
                            DepartmentId = 2,
                            Name = "Procurement",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 10,
                            DepartmentId = 2,
                            Name = "ERP",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 11,
                            DepartmentId = 2,
                            Name = "Contract Management",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 12,
                            DepartmentId = 2,
                            Name = "Project/ Business Performance Analysis and Reporting",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 13,
                            DepartmentId = 2,
                            Name = "ERP Customization",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 14,
                            DepartmentId = 2,
                            Name = "Additional",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 15,
                            DepartmentId = 3,
                            Name = "Financial Statements preparation and analysis",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 16,
                            DepartmentId = 3,
                            Name = "Payments",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 17,
                            DepartmentId = 3,
                            Name = "Taxation",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 18,
                            DepartmentId = 3,
                            Name = "Banking",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 19,
                            DepartmentId = 3,
                            Name = "Learning and Development",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 20,
                            DepartmentId = 3,
                            Name = "Audit & Compliances",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 21,
                            DepartmentId = 3,
                            Name = "Additional",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 22,
                            DepartmentId = 4,
                            Name = "Talent acquisition",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 23,
                            DepartmentId = 4,
                            Name = "HR Administration",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 24,
                            DepartmentId = 4,
                            Name = "Performance Management, R&R",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 25,
                            DepartmentId = 4,
                            Name = "Succession Planning/Leadership Development",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 26,
                            DepartmentId = 4,
                            Name = "Training & Development",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 27,
                            DepartmentId = 4,
                            Name = "Audit & Compliances",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 28,
                            DepartmentId = 4,
                            Name = "Additional",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 29,
                            DepartmentId = 5,
                            Name = "Hardware/Software procurement",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 30,
                            DepartmentId = 5,
                            Name = "IT Support/troubleshooting",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 31,
                            DepartmentId = 5,
                            Name = "Network/Server maintenance",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 32,
                            DepartmentId = 5,
                            Name = "Digital innovation support",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 33,
                            DepartmentId = 5,
                            Name = "Learning and Development",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 34,
                            DepartmentId = 5,
                            Name = "SLA/Policy Compliance",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 35,
                            DepartmentId = 5,
                            Name = "Additional",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 36,
                            DepartmentId = 6,
                            Name = "Brand/Corporate Communication",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 37,
                            DepartmentId = 6,
                            Name = "Marketing Material development",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 38,
                            DepartmentId = 6,
                            Name = "Digital Marketing",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 39,
                            DepartmentId = 6,
                            Name = "Association Membership and networking",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 40,
                            DepartmentId = 6,
                            Name = "Learning & Development",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 41,
                            DepartmentId = 6,
                            Name = "Audit/ Compliances",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 42,
                            DepartmentId = 6,
                            Name = "Additional",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 43,
                            DepartmentId = 7,
                            Name = "Contract drafting & Review",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 44,
                            DepartmentId = 7,
                            Name = "Handling legal issues and cases",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 45,
                            DepartmentId = 7,
                            Name = "REIT",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 46,
                            DepartmentId = 7,
                            Name = "Learning & Development",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 47,
                            DepartmentId = 7,
                            Name = "Audit/ Compliances",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 48,
                            DepartmentId = 7,
                            Name = "Additional",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 49,
                            DepartmentId = 8,
                            Name = "Hiring/ de-hiring of premises/ Guest Houses",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 50,
                            DepartmentId = 8,
                            Name = "Procurement/Disposal of furniture, fixtures, monthly consumables",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 51,
                            DepartmentId = 8,
                            Name = "Travel Booking",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 52,
                            DepartmentId = 8,
                            Name = "Handling office boys, security",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 53,
                            DepartmentId = 8,
                            Name = "Learning & Development",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 54,
                            DepartmentId = 8,
                            Name = "Audit/ Compliances",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 55,
                            DepartmentId = 8,
                            Name = "Additional",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 56,
                            DepartmentId = 9,
                            Name = "Secretarial",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 57,
                            DepartmentId = 9,
                            Name = "Fund Raising",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 58,
                            DepartmentId = 9,
                            Name = "Acquisition",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 59,
                            DepartmentId = 9,
                            Name = "REIT",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 60,
                            DepartmentId = 9,
                            Name = "Learning & Development",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 61,
                            DepartmentId = 9,
                            Name = "Audit & Compliances",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 62,
                            DepartmentId = 9,
                            Name = "Additional",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 63,
                            DepartmentId = 10,
                            Name = "Business Development - Pipeline creation",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 64,
                            DepartmentId = 10,
                            Name = "Business Development - Bidding",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 65,
                            DepartmentId = 10,
                            Name = "New Product/service development",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 66,
                            DepartmentId = 10,
                            Name = "Business Performance support and Analysis",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 67,
                            DepartmentId = 10,
                            Name = "Learning & Development",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 68,
                            DepartmentId = 10,
                            Name = "Audit & Compliances",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 69,
                            DepartmentId = 10,
                            Name = "Additional",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 70,
                            DepartmentId = 11,
                            Name = "Business Development - Pipeline creation",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 71,
                            DepartmentId = 11,
                            Name = "Business Development - Bidding",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 72,
                            DepartmentId = 11,
                            Name = "Project Quality Delivery",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 73,
                            DepartmentId = 11,
                            Name = "Project and Business Administration",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 74,
                            DepartmentId = 11,
                            Name = "Learning & Development",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 75,
                            DepartmentId = 11,
                            Name = "Audit & Compliances",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 76,
                            DepartmentId = 11,
                            Name = "Additional",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 77,
                            DepartmentId = 12,
                            Name = "Business Development - Pipeline creation",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 78,
                            DepartmentId = 12,
                            Name = "Business Development - Bidding",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 79,
                            DepartmentId = 12,
                            Name = "Project Quality Delivery",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 80,
                            DepartmentId = 12,
                            Name = "Project Commercial success",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 81,
                            DepartmentId = 12,
                            Name = "Learning & Development",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 82,
                            DepartmentId = 12,
                            Name = "Audit & Compliances",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 83,
                            DepartmentId = 12,
                            Name = "Additional",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 84,
                            DepartmentId = 13,
                            Name = "Business Development - Pipeline creation",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 85,
                            DepartmentId = 13,
                            Name = "Business Development - Bidding",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 86,
                            DepartmentId = 13,
                            Name = "Bid Quality Delivery",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 87,
                            DepartmentId = 13,
                            Name = "Bid Commercial success",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 88,
                            DepartmentId = 13,
                            Name = "Learning & Development",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 89,
                            DepartmentId = 13,
                            Name = "Audit & Compliances",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 90,
                            DepartmentId = 13,
                            Name = "Additional",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 91,
                            DepartmentId = 14,
                            Name = "Business Development - Pipeline creation",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 92,
                            DepartmentId = 14,
                            Name = "Business Development - Bidding",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 93,
                            DepartmentId = 14,
                            Name = "Project Quality Delivery",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 94,
                            DepartmentId = 14,
                            Name = "Project Commercial success",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 95,
                            DepartmentId = 14,
                            Name = "Learning & Development",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 96,
                            DepartmentId = 14,
                            Name = "Audit & Compliances",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 97,
                            DepartmentId = 14,
                            Name = "Additional",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 98,
                            DepartmentId = 15,
                            Name = "Learning & Development",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 99,
                            DepartmentId = 15,
                            Name = "Audit & Compliances",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 100,
                            DepartmentId = 15,
                            Name = "Additional",
                            Status = "Active"
                        });
                });

            modelBuilder.Entity("TimeSheet.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("ProjectCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("TimeSheet.Models.ProjectMilestone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<long>("AssignedHours")
                        .HasColumnType("bigint");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("MilestoneCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MilestoneDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("PendingWorkingHours")
                        .HasColumnType("bigint");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("TaskCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaskDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TimeSheetLineNumber")
                        .HasColumnType("int");

                    b.Property<string>("TimeSheetNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("TotalWorkingHours")
                        .HasColumnType("bigint");

                    b.Property<string>("WbsId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectMilestones");
                });

            modelBuilder.Entity("TimeSheet.Models.SubmissionLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ApprovedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ApproverId")
                        .HasColumnType("int");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<long>("Hours")
                        .HasColumnType("bigint");

                    b.Property<string>("RejectionRemarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SubmissionDate")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("TimesheetDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("ApproverId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("SubmissionLogs");
                });

            modelBuilder.Entity("TimeSheet.Models.Timesheet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<long>("Hours")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsBillable")
                        .HasColumnType("bit");

                    b.Property<int?>("MilestoneId")
                        .HasColumnType("int");

                    b.Property<int?>("ProjectMilestoneId")
                        .HasColumnType("int");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("MilestoneId");

                    b.HasIndex("ProjectMilestoneId");

                    b.ToTable("Timesheets");
                });

            modelBuilder.Entity("TimeSheet.Models.WorkingHours", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<long>("Hours")
                        .HasColumnType("bigint");

                    b.Property<long>("HoursLeft")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("WorkingHours");
                });

            modelBuilder.Entity("TimeSheet.Models.Employee", b =>
                {
                    b.HasOne("TimeSheet.Models.Employee", "Approver")
                        .WithMany()
                        .HasForeignKey("ApproverId");

                    b.HasOne("TimeSheet.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Approver");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("TimeSheet.Models.Milestone", b =>
                {
                    b.HasOne("TimeSheet.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("TimeSheet.Models.Project", b =>
                {
                    b.HasOne("TimeSheet.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("TimeSheet.Models.ProjectMilestone", b =>
                {
                    b.HasOne("TimeSheet.Models.Project", "Project")
                        .WithMany("ProjectMilestones")
                        .HasForeignKey("ProjectId");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("TimeSheet.Models.SubmissionLog", b =>
                {
                    b.HasOne("TimeSheet.Models.Employee", "Approver")
                        .WithMany()
                        .HasForeignKey("ApproverId");

                    b.HasOne("TimeSheet.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId");

                    b.Navigation("Approver");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("TimeSheet.Models.Timesheet", b =>
                {
                    b.HasOne("TimeSheet.Models.Employee", "Employee")
                        .WithMany("Timesheets")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TimeSheet.Models.Milestone", "Milestone")
                        .WithMany("Timesheets")
                        .HasForeignKey("MilestoneId");

                    b.HasOne("TimeSheet.Models.ProjectMilestone", "ProjectMilestone")
                        .WithMany("Timesheets")
                        .HasForeignKey("ProjectMilestoneId");

                    b.Navigation("Employee");

                    b.Navigation("Milestone");

                    b.Navigation("ProjectMilestone");
                });

            modelBuilder.Entity("TimeSheet.Models.WorkingHours", b =>
                {
                    b.HasOne("TimeSheet.Models.Employee", "Employee")
                        .WithMany("WorkingHours")
                        .HasForeignKey("EmployeeId");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("TimeSheet.Models.Employee", b =>
                {
                    b.Navigation("Timesheets");

                    b.Navigation("WorkingHours");
                });

            modelBuilder.Entity("TimeSheet.Models.Milestone", b =>
                {
                    b.Navigation("Timesheets");
                });

            modelBuilder.Entity("TimeSheet.Models.Project", b =>
                {
                    b.Navigation("ProjectMilestones");
                });

            modelBuilder.Entity("TimeSheet.Models.ProjectMilestone", b =>
                {
                    b.Navigation("Timesheets");
                });
#pragma warning restore 612, 618
        }
    }
}
